version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  TOOLSET: v140
  ToolsVersion: 14.0
before_build:
- cmd: nuget restore
build:
  project: Cub.sln
  verbosity: minimal
notifications:
- provider: Slack
  incoming_webhook:
    secure: VTW6QR2dv7aNlFnRdadruW7qw1BxL4PuY6VHOGvBXigrbnS7zUp/GXgWX+4yd3aTpZgYJYk0VhszvRqxsUAlVHN7pFbvEhGxxx9YExqpMyk=
  channel: '#id'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
